
require('./assets/Scripts/Common/DatabaseManager');
require('./assets/Scripts/Common/DialogManager');
require('./assets/Scripts/Common/GameState');
require('./assets/Scripts/Common/ScreenManager');
require('./assets/Scripts/Gameplay/AutoMoving');
require('./assets/Scripts/Gameplay/BlockScript');
require('./assets/Scripts/Gameplay/GameManager');
require('./assets/Scripts/Gameplay/PlayerScript');
require('./assets/Scripts/Popup/EndGamePopup');
require('./assets/Scripts/Screen/Home/HomePlayerItem');
require('./assets/Scripts/Screen/Home/HomePlayerScript');
require('./assets/Scripts/Screen/Home/HomeScript');
require('./assets/Scripts/Ultilities/CustomEventManager');
require('./assets/Scripts/Ultilities/NumberUltilities');
require('./assets/Scripts/Ultilities/SimplePool');
require('./assets/Scripts/Ultilities/SoundManager');
require('./assets/Scripts/facebook/FBConfig');
require('./assets/Scripts/facebook/FBGlobal');
